name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: npm ci
        
      - name: Update vite config
        run: |
          sed -i 's|base: '\''/fliessgeschwindigkeit/'\''|base: '\''/fliessgeschwindigkeit_svelte/'\''|' vite.config.js
          cat vite.config.js
        
      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build process completed"
        env:
          NODE_ENV: production
        
      - name: Verify build output
        run: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nDist directory contents:"
          if [ -d "dist" ]; then
            ls -la dist/
            if [ ! -f "dist/index.html" ]; then
              echo "index.html not found in dist directory!"
              exit 1
            fi
          else
            echo "dist directory not found!"
            exit 1
          fi
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3